export enum UserStatus {
  ACTIVE = 'ACTIVE',
  IN_ACTIVE = 'IN_ACTIVE',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  LEFT_REQUESTING = 'LEFT_REQUESTING',
  TERMINATED = 'TERMINATED',
}

export enum UserType {
  STUDENT = 'STUDENT',
  TEACHER = 'TEACHER',
}
